[package]
name = "serde_arrow"
version = "0.7.0"
authors = ["Christopher Prohm <mail@cprohm.de>"]
edition = "2021"
description  = "convert sequences of structs / maps to arrow tables"
readme = "../Readme.md"
repository = "https://github.com/chmp/serde_arrow"
license = "MIT"

[lib]
bench = false

[[bench]]
name = "arrow2"
required-features = ["arrow2-0-17", "arrow-39"]
harness = false

[package.metadata.docs.rs]
features = ["arrow2-0-17", "arrow-39"]

[features]
default = []

arrow-41 = ["dep:arrow-array-41", "dep:arrow-schema-41", "dep:arrow-data-41", "dep:arrow-buffer-41"]
arrow-39 = ["dep:arrow-array-39", "dep:arrow-schema-39", "dep:arrow-data-39", "dep:arrow-buffer-39"]
arrow-38 = ["dep:arrow-array-38", "dep:arrow-schema-38", "dep:arrow-data-38", "dep:arrow-buffer-38"]
arrow-37 = ["dep:arrow-array-37", "dep:arrow-schema-37", "dep:arrow-data-37", "dep:arrow-buffer-37"]
arrow-36 = ["dep:arrow-array-36", "dep:arrow-schema-36", "dep:arrow-data-36", "dep:arrow-buffer-36"]
arrow-35 = ["dep:arrow-array-35", "dep:arrow-schema-35", "dep:arrow-data-35", "dep:arrow-buffer-35"]

[dependencies]
arrow-array-41 = { package = "arrow-array", version = "41", optional = true }
arrow-buffer-41 = { package = "arrow-buffer", version = "41", optional = true }
arrow-data-41 = { package = "arrow-data", version="41", optional = true, features = ["ffi"] }
arrow-schema-41 = { package = "arrow-schema", version = "41", optional = true }


arrow-array-39 = { package = "arrow-array", version = "39", optional = true }
arrow-buffer-39 = { package = "arrow-buffer", version = "39", optional = true }
arrow-data-39 = { package = "arrow-data", version="39", optional = true, features = ["ffi"] }
arrow-schema-39 = { package = "arrow-schema", version = "39", optional = true }

arrow-array-38 = { package = "arrow-array", version = "38", optional = true }
arrow-buffer-38 = { package = "arrow-buffer", version = "38", optional = true }
arrow-data-38 = { package = "arrow-data", version="38", optional = true, features = ["ffi"] }
arrow-schema-38 = { package = "arrow-schema", version = "38", optional = true }

arrow-array-37 = { package = "arrow-array", version = "37", optional = true }
arrow-buffer-37 = { package = "arrow-buffer", version = "37", optional = true }
arrow-data-37 = { package = "arrow-data", version="37", optional = true, features = ["ffi"]  }
arrow-schema-37 = { package = "arrow-schema", version = "37", optional = true }

arrow-array-36 = { package = "arrow-array", version = "36", optional = true }
arrow-buffer-36 = { package = "arrow-buffer", version = "36", optional = true }
arrow-data-36 = { package = "arrow-data", version="36", optional = true, features = ["ffi"]  }
arrow-schema-36 = { package = "arrow-schema", version = "36", optional = true }

arrow-array-35 = { package = "arrow-array", version = "35", optional = true }
arrow-buffer-35 = { package = "arrow-buffer", version = "35", optional = true }
arrow-data-35 = { package = "arrow-data", version="35", optional = true, features = ["ffi"] }
arrow-schema-35 = { package = "arrow-schema", version = "35", optional = true }

arrow2-0-16 = { package = "arrow2", version = "0.16", optional = true }
arrow2-0-17 = { package = "arrow2", version = "0.17", optional = true }

serde = "1.0"

# TODO: make optional, only required for str -> date conversions
chrono = "0.4"

[dev-dependencies]
anyhow = "1"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.8"

arrow-json-39 = { package = "arrow-json", version = "39" }

# for benchmarks
criterion = "0.4"
arrow2_convert = "0.5.0"
